name: API tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start SUT in background
        run: nohup java -jar ./artifacts/app-mbank.jar > sut.log 2>&1 &

      - name: Wait for service to start
        run: sleep 10

      - name: Run tests
        run: ./gradlew test
